// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Ohhs3Go51Z_K05mRj6pFlZv30ot2mr0',
    appId: '1:679917518364:web:419fcdd74a7c83310169d9',
    messagingSenderId: '679917518364',
    projectId: 'aisa-fibernet',
    authDomain: 'aisa-fibernet.firebaseapp.com',
    storageBucket: 'aisa-fibernet.firebasestorage.app',
    measurementId: 'G-C9X35J4GQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUoxo2sDkRMZe5rsp0WtTySdRC59WnZj8',
    appId: '1:679917518364:android:e87d49df919dda5d0169d9',
    messagingSenderId: '679917518364',
    projectId: 'aisa-fibernet',
    storageBucket: 'aisa-fibernet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAemRv3td1EdDvMf1PqFunSNH8p3ZzaqMA',
    appId: '1:679917518364:ios:29c1fcdc5866d5350169d9',
    messagingSenderId: '679917518364',
    projectId: 'aisa-fibernet',
    storageBucket: 'aisa-fibernet.firebasestorage.app',
    iosBundleId: 'com.example.asiaFibernet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAemRv3td1EdDvMf1PqFunSNH8p3ZzaqMA',
    appId: '1:679917518364:ios:29c1fcdc5866d5350169d9',
    messagingSenderId: '679917518364',
    projectId: 'aisa-fibernet',
    storageBucket: 'aisa-fibernet.firebasestorage.app',
    iosBundleId: 'com.example.asiaFibernet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2Ohhs3Go51Z_K05mRj6pFlZv30ot2mr0',
    appId: '1:679917518364:web:f8fc81f412225cb70169d9',
    messagingSenderId: '679917518364',
    projectId: 'aisa-fibernet',
    authDomain: 'aisa-fibernet.firebaseapp.com',
    storageBucket: 'aisa-fibernet.firebasestorage.app',
    measurementId: 'G-QCGN4BQC99',
  );
}
